### PR TITLE
#46 - Changing user's password

### LINKED ISSUE #46: Security: Changing user's password
Creating new api for changing user's password:

`PUT v1/users/change-password`

User can change only his password, so injecting user context. Accepts PasswordChangeDTO

```java
class PasswordChangeDTO {
    String pasword;
    String newPassword;
}
```

Finds user by password and @InjectUserContext.email, checks if optional.isPresent, if so, changes password to new password (HASHED). If no user found, throw user input exception "Current password didn't match."

### PR DESCRIPTION
**Pull request by JBarcuk**

### CODE REVIEW

File: src/main/java/cz/tstrecha/timetracker/controller/v1/UserController.java [hunk 1]
```diff
@@ -60,4 +61,10 @@ public ResponseEntity<LoginResponseDTO> changeContext(@RequestParam Long id,
                                                           @InjectUserContext UserContext userContext){
         return new ResponseEntity<>(userService.changeContext(id, userContext), HttpStatus.OK);
     }
+
+    @PutMapping("/change-password")
+    public ResponseEntity<LoginResponseDTO> changePassword(@RequestBody PasswordChangeDTO passwordChangeDTO,
+                                                  @InjectUserContext UserContext userContext){
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/controller/v1/UserController.java]: Reformatte

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 2]
```diff
@@ -171,4 +172,24 @@ public LoginResponseDTO loginUser(LoginRequestDTO loginRequest) {
...
         return new LoginResponseDTO(true, token, refreshToken);
     }
+
+    @Override
+    @Transactional
+    public LoginResponseDTO changePassword(PasswordChangeDTO passwordChangeDTO, UserContext userContext) {
+        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(userContext.getEmail(), passwordChangeDTO.getPassword()));
+        var user = userRepository.findByEmail(userContext.getEmail())
+                .orElseThrow(() -> new UsernameNotFoundException("No user exists for email [" + userContext.getEmail() + "]"));
+        if (IntStream.of(0, passwordChangeDTO.getNewPassword().length() - 1).noneMatch(i -> Character.isDigit(passwordChangeDTO.getNewPassword().charAt(i)))) {
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java]: DRY => This code already exists when registering -> move to separate method validatePassword()

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 3]
```diff
@@ -171,4 +172,24 @@ public LoginResponseDTO loginUser(LoginRequestDTO loginRequest) {
...
+            throw new UserInputException("Password should contain at least 1 digit.", ErrorTypeCode.PASSWORD_DOESNT_CONTAIN_DIGIT, "PasswordChangeDTO");
+        }
+        var passwordHashed = passwordEncoder.encode(passwordChangeDTO.getNewPassword());
+        user.setPasswordHashed(passwordHashed);
+        userRepository.save(user);
+
+        var token = authenticationService.generateToken(user, null);
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java]: What if user is authorized as someone else?

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 4]
```diff
@@ -171,4 +172,24 @@ public LoginResponseDTO loginUser(LoginRequestDTO loginRequest) {
...
+        var refreshToken = authenticationService.generateRefreshToken(user.getId(), user.getId());
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java]: What if user is authorized as someone else?

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 5]
```diff
@@ -171,4 +172,24 @@ public LoginResponseDTO loginUser(LoginRequestDTO loginRequest) {
...
+        return new LoginResponseDTO(true, token, refreshToken);
+    }
+
+
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java:195]:
```suggestion
```

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 6]
```diff
@@ -171,4 +172,24 @@ public LoginResponseDTO loginUser(LoginRequestDTO loginRequest) {
...
+        }
+        var passwordHashed = passwordEncoder.encode(passwordChangeDTO.getNewPassword());
+        user.setPasswordHashed(passwordHashed);
+        userRepository.save(user);
+
+        var token = authenticationService.generateToken(user, null);
+        var refreshToken = authenticationService.generateRefreshToken(user.getId(), user.getId());
+        return new LoginResponseDTO(true, token, refreshToken);
+    }
+
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java:189]:
```suggestion
```

**Review by TStrecha — CHANGES_REQUESTED** [review]

File: src/main/java/cz/tstrecha/timetracker/controller/v1/UserController.java [hunk 7]
```diff
@@ -60,4 +61,10 @@ public ResponseEntity<LoginResponseDTO> changeContext(@RequestParam Long id,
                                                           @InjectUserContext UserContext userContext){
         return new ResponseEntity<>(userService.changeContext(id, userContext), HttpStatus.OK);
     }
+
+    @PutMapping("/change-password")
+    public ResponseEntity<LoginResponseDTO> changePassword(@RequestBody PasswordChangeDTO passwordChangeDTO,
+                                                           @InjectUserContext UserContext userContext){
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/controller/v1/UserController.java]:
```suggestion
                                                           @InjectUserContext UserContext userContext) {
```

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java (hunk 2 above)
Comment (TStrecha) [reply src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java]: You didn't really changed this, you're validating password still here

File: src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java [hunk 8]
```diff
@@ -165,10 +167,32 @@ public LoginResponseDTO changeContext(Long id, UserContext userContext) {
...
+        var passwordHashed = passwordEncoder.encode(passwordChangeDTO.getNewPassword());
+        user.setPasswordHashed(passwordHashed);
+        userRepository.save(user);
+
+        var token = authenticationService.generateToken(user, userContext.getLoggedAs());
+        var refreshToken = authenticationService.generateRefreshToken(user.getId(), userContext.getLoggedAs().getId());
+        return new LoginResponseDTO(true, token, refreshToken);
+    }
+
+    private UserEntity validatePassword(String email, String password){
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/UserServiceImpl.java]: Naming isn't clear, this doesn't validate password, it authenticates and retrieves user

**Review by TStrecha — CHANGES_REQUESTED** [review]

**Review by TStrecha — APPROVED** [review]
