### PR TITLE
#42 - Authorizing as other user doesn't check for relationship valida…

### LINKED ISSUE #42: Security: Authorizing as other user doesn't check for relationship validation
When changing context:

```
        var contextUserDTO = userContext.getRelationshipsReceiving().stream()
                .filter(relation -> relation.getId().equals(id))
                .findFirst()
                .orElseThrow(() -> new PermissionException("User dont have permission to change context to id [" + id + "]", ErrorTypeCode.USER_DOESNT_HAVE_PERMISSION_TO_CHANGE_CONTEXT));
```

This only checks if realtionship between two users exists, but doesn't check if relationship is active between them - check also for `Relationship.validFrom` and `Relationship.validTo` -> you can just add it into `ContextUserDTO`, no need to open persistence in this method.

### PR DESCRIPTION
**Pull request by JBarcuk**

### CODE REVIEW

File: src/test/java/cz/tstrecha/timetracker/core/integration/AuthIT.java [hunk 1]
```diff
@@ -123,6 +125,7 @@ public void test03_loginUser_success() {
         var algorithmHeader = objectMapper.readValue(header, AlgorithmHeader.class);
         Assertions.assertEquals(SignatureAlgorithm.HS256, algorithmHeader.alg);
 
+        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```
Comment (TStrecha) [inline src/test/java/cz/tstrecha/timetracker/core/integration/AuthIT.java]: Into object mapper bean

File: src/main/java/cz/tstrecha/timetracker/TimeTrackerApplication.java [hunk 2]
```diff
@@ -1,13 +1,23 @@
...
     public static void main(String[] args) {
         SpringApplication.run(TimeTrackerApplication.class, args);
     }
+    
+    @Bean
+    public ObjectMapper objectMapper(){
+        var mapper = new ObjectMapper();
+        mapper.registerModule(new JavaTimeModule());
+        return mapper;
+    }
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/TimeTrackerApplication.java]:
```suggestion
```

File: pom.xml [hunk 3]
```diff
@@ -116,6 +116,11 @@
             <version>2.3.2</version>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>com.fasterxml.jackson.datatype</groupId>
+            <artifactId>jackson-datatype-jsr310</artifactId>
+            <version>2.14.2</version>
```
Comment (TStrecha) [inline pom.xml]: into properties, including other dependencies above

**Review by TStrecha — CHANGES_REQUESTED** [review]

**Review by TStrecha — APPROVED** [review]
