### PR TITLE
#54 - Updating settings

### LINKED ISSUE #54: Users: Updating settings
Adding new api `PUT v1/settings/`

Accepts `@Valid SettingsCreateUpdateDTO` from https://github.com/TStrecha/time-tracker/issues/52 

Finds settings entity by id, if `validTo != null && validTo isAfter now` throws user input exception "You cannot change no longer valid settings."

Otherwise just update the data and save it.

### PR DESCRIPTION
**Pull request by JBarcuk**

### CODE REVIEW

File: src/main/java/cz/tstrecha/timetracker/controller/v1/SettingsController.java [hunk 1]
```diff
@@ -32,4 +33,10 @@ public ResponseEntity<SettingsCreateUpdateDTO> createUserSetting(@RequestBody @V
                                                                      @InjectLoggedUser LoggedUser loggedUser){
         return new ResponseEntity<>(settingsService.createSetting(setting, loggedUser), HttpStatus.CREATED);
     }
+
+    @PutMapping
+    public ResponseEntity<SettingsCreateUpdateDTO> updateUserSetting(@RequestBody @Valid SettingsCreateUpdateDTO setting,
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/controller/v1/SettingsController.java:41]: @PermissionCheck("settings.create") and also add it to the creation method

File: src/main/resources/error_codes_cs.properties [hunk 2]
```diff
@@ -10,6 +10,9 @@ TaskIsntActive = Tento úkol není aktivní
 TaskAlreadyDone = Tento úkol je již splněn
 ValidFromIsAfterValidTo = Čas ukončení nastavení nemůže být dříve než počátek
 SettingIntersects = Již existují nastavení, se kterými by se nové nastavení protínalo.
+SettingNotFoundById = Nastavení s tímto id nebylo nalezeno
+SettingNoLongerValid = Nemůžete změnit nastavení, které již není platné
+SettingHasSameName = Nastavení nemohou mít stejná jména
```
Comment (TStrecha) [inline src/main/resources/error_codes_cs.properties]:
```suggestion
SettingHasSameName = Již existujie nastavení, které má stejný název.
```

File: src/main/java/cz/tstrecha/timetracker/constant/ErrorTypeCode.java [hunk 3]
```diff
@@ -18,6 +18,9 @@ public enum ErrorTypeCode {
     TASK_ALREADY_DONE("TaskAlreadyDone"),
     VALID_FROM_AFTER_VALID_TO("ValidFromIsAfterValidTo"),
     INTERSECTS_WITH_OTHER_SETTINGS("SettingIntersects"),
+    SETTING_NOT_FOUND_BY_ID("SettingNotFoundById"),
+    SETTING_NO_LONGER_VALID("SettingNoLongerValid"),
+    SETTING_HAS_SAME_NAME("SettingHasSameName"),
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/constant/ErrorTypeCode.java]: More of like "SettingsNameNotUnique"

File: src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java [hunk 4]
```diff
@@ -41,4 +43,31 @@ public SettingsCreateUpdateDTO createSetting(SettingsCreateUpdateDTO settingsCre
...
+
+        if (setting.getValidTo() != null && setting.getValidTo().isBefore(LocalDate.now())){
+            throw new UserInputException("You cannot change no longer valid settings.", ErrorTypeCode.SETTING_NO_LONGER_VALID, "SettingsCreateUpdateDTO");
+        }
+
+        if (settingsCreateUpdateDTO.getValidTo() != null && settingsCreateUpdateDTO.getValidTo().isBefore(setting.getValidFrom())){
+            throw new UserInputException("Valid from cannot be after valid to.", ErrorTypeCode.VALID_FROM_AFTER_VALID_TO, "SettingsCreateUpdateDTO");
+        }
+
+        if (userSettingsRepository.existsByUserAndNameAndIdIsNot(user.getUserEntity(), settingsCreateUpdateDTO.getName(), settingsCreateUpdateDTO.getId())){
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java:65]: Check this also when creating new setting

File: src/main/resources/error_codes_en_US.properties [hunk 5]
```diff
@@ -10,6 +10,9 @@ TaskIsntActive = This task isn't active.
 TaskAlreadyDone = This task is already done.
 ValidFromIsAfterValidTo = Valid from cannot be after valid to.
 SettingIntersects = There are active settings that would new settings intersect with.
+SettingNotFoundById = Setting not found by this id.
+SettingNoLongerValid = You cannot change no longer valid settings.
+SettingHasSameName = Settings cannot have same name.
```
Comment (TStrecha) [inline src/main/resources/error_codes_en_US.properties]:
```suggestion
SettingHasSameName = There is already a setting with this name.
```

File: src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java [hunk 6]
```diff
@@ -41,4 +43,31 @@ public SettingsCreateUpdateDTO createSetting(SettingsCreateUpdateDTO settingsCre
...
+        }
+
+        settingsMapper.updateSetting(settingsCreateUpdateDTO, setting);
+
+        userSettingsRepository.save(setting);
+
+        return settingsMapper.toDTO(setting);
+    }
+
+
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java]:
```suggestion
```

File: src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java [hunk 7]
```diff
@@ -41,4 +43,31 @@ public SettingsCreateUpdateDTO createSetting(SettingsCreateUpdateDTO settingsCre
...
+            throw new UserInputException("Settings cannot have same name.", ErrorTypeCode.SETTING_HAS_SAME_NAME, "SettingsCreateUpdateDTO");
+        }
+
+        settingsMapper.updateSetting(settingsCreateUpdateDTO, setting);
+
+        userSettingsRepository.save(setting);
+
+        return settingsMapper.toDTO(setting);
+    }
+
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java]:
```suggestion
```

**Review by TStrecha — CHANGES_REQUESTED** [review]

File: src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java [hunk 8]
```diff
@@ -26,6 +28,10 @@ public SettingsCreateUpdateDTO createSetting(SettingsCreateUpdateDTO settingsCre
             throw new UserInputException("Valid from cannot be after valid to.", ErrorTypeCode.VALID_FROM_AFTER_VALID_TO, "SettingsCreateUpdateDTO");
         }
 
+        if (userSettingsRepository.existsByUserAndNameAndIdIsNot(user.getUserEntity(), settingsCreateUpdateDTO.getName(), settingsCreateUpdateDTO.getId())){
```
Comment (TStrecha) [inline src/main/java/cz/tstrecha/timetracker/service/impl/SettingsServiceImpl.java]:
```suggestion
        if (userSettingsRepository.existsByUserAndNameAndIdIsNot(user.getUserEntity(), settingsCreateUpdateDTO.getName(), null)){
```

**Review by TStrecha — APPROVED** [review]
